# Generated by Django 5.1.3 on 2024-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name (English)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='Ingredients')),
                ('slug', models.SlugField(unique=True)),
                ('article', models.CharField(max_length=50, verbose_name='Article')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('aviable_num', models.IntegerField(default=0, verbose_name='Available Quantity')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage')),
                ('brand_flavor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand/Flavor')),
                ('diet_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diet Type')),
                ('age_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age Range')),
                ('item_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Form')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width (cm)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (cm)')),
                ('expiration_months', models.IntegerField(blank=True, null=True, verbose_name='Months to Expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tags', models.ManyToManyField(blank=True, to='shop.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
