# Generated by Django 5.1.3 on 2024-11-13 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VIEWED', 'Viewed'), ('DONE', 'Done')], default='NEW', max_length=10, verbose_name='Status')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Time')),
            ],
            options={
                'verbose_name': 'Call Request',
                'verbose_name_plural': 'Call Requests',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Comment')),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Rating (1-5)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-time'],
            },
        ),
    ]
