# Generated by Django 5.1.3 on 2024-11-13 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_callrequest_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Subscription Email')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Is Subscribed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('topics', models.JSONField(blank=True, default=dict, verbose_name='Topics Preferences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'unique_together': {('user', 'email')},
            },
        ),
    ]
